name: Web App Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-web-app:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USER }}/web_app .

    - name: Run the Web App Container
      run: docker run -d -p 80:80 --name web_app ${{ secrets.DOCKER_USER }}/web_app

    - name: Verify Running Containers
      run: docker ps -a

    - name: Run Tests
      uses: liatrio/github-actions/apprentice-action@v1.0.0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

    - name: Tag Docker Image
      run: docker tag ${{ secrets.DOCKER_USER }}/web_app gcr.io/${{ secrets.GCP_PROJECT }}/web_app

    - name: Docker Push
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/web_app

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GC_CREDENTIALS }}

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_APP }} \
          --image=gcr.io/${{ secrets.GCP_PROJECT }}/web_app \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
